plugins {
    id "com.android.application"
}

android {
    namespace "com.teffbeauty.exclusivo.v13"
    compileSdk 35

    defaultConfig {
        applicationId "com.teffbeauty.exclusivo.v21"
        minSdk 23
        targetSdk 35
        versionCode 21
        versionName "1.0.21"
    }

    sourceSets {
        main {
            assets.srcDirs += ["$buildDir/generated/assets/teffWeb"]
        }
    }
}

tasks.register("syncTeffWebAssets", Copy) {
    from("$rootDir/web")
    into("$buildDir/generated/assets/teffWeb")
}

tasks.matching { it.name == "preBuild" }.configureEach {
    dependsOn("syncTeffWebAssets")
}
